### ISSUE TITLE
Feat: Re-use flexible-rate-limit class instance

### ISSUE THREAD

**Issue by intellix** [ravangen/graphql-rate-limit#214]
Was thinking that I'd like to secure our Express-based authentication routes using rate-limiter-flexible but would require instantiating another class just for use there.

It'd be nice if this library accepted an instance of `RateLimiterRedis` instead of the class reference so you can share it

**Comment by ravangen** [comment]
Is there a specific concern with multiple instances of `RateLimiterRedis`? Or is the desire to reuse the same instance?

My initial reaction is that this may not possible as the implementation of this directive relies on passing the directive's arguments in the construction of a `RateLimiterAbstract` which includes `RateLimiterRedis`. This configures the behaviour of what it means to "consume" some of the limit.

https://github.com/ravangen/graphql-rate-limit/blob/40bdd7f078dd5a3cf8090a36bb4d3096e6465e3f/src/index.ts#L239-L255

Assuming each usage of the GraphQL directive has the same configuration, the library would only have one instance, but it doesn't expose its internals to provide you a reference.

The Redis client instance can still be reused as it is provided as `RateLimiterRedis` constructor options, leveraging the same underlying network connection.

**Comment by intellix** [comment]
ok yep exactly as you said, you need a separate instance per use. I was expecting that to be fairly heavy but haven't really looked inside the RateLimiterRedis class. I guess we can close this as irrelevant :)
