### ISSUE TITLE
[QUESTION]: Is this production ready?

### ISSUE THREAD

**Issue by simplecommerce** [ravangen/graphql-rate-limit#229]
Hi,

I wanted to know if this library is tested and ready to be used in production environment?

Thanks!

**Comment by ravangen** [comment]
I believe it is production ready, and I know it has been in use for over 2 years in at least one fintech company.

There are [tests at `src/__tests__/index.spec.ts`](https://github.com/ravangen/graphql-rate-limit/blob/master/src/__tests__/index.spec.ts) and you can see a [coverage report here](https://app.codecov.io/gh/ravangen/graphql-rate-limit).

Ultimately the decision is yours to make 😄 Feedback welcome!

**Comment by simplecommerce** [comment]
@ravangen Thank you for your reply!!

**Comment by simplecommerce** [comment]
Quick question, is there a way to ban a user permanently if they keep maxing out the limit?
For example, if I set a limit of 5 every hour, but I would like to ban a user after they try more than 15 times in a day?

I assume I would have to do my own logic using onLimit?

**Comment by ravangen** [comment]
This library does not have a concept of a ban. Using `onLimit` sounds like a good place to start to know when to trigger the ban, and then it enforcement depends if you want that ban to apply schema wide (custom), or per field (default).

**Comment by chenrui333** [comment]
We (meetup) are also using this library in production as well.
