### ISSUE TITLE
How is it possible to integrate with the apollo/gateway in a federated graph?

### ISSUE THREAD

**Issue by sbilello** [ravangen/graphql-rate-limit#230]
HI!
Can you please show an example of how is it possible to integrate with the apollo/gateway in a federated graph?

**Comment by ravangen** [comment]
👋 I'm not familiar with the Apollo Gateway configuration specifics, but I believe this library would be considered an [executable directive](https://www.apollographql.com/docs/federation/gateway/#executable-directives). My assumption is that you could setup the rate limit directive on your subgraphs, and then put the gateway server in front of them.

> At composition time, `ApolloGateway` makes sure that **all of your subgraphs define the exact same set of executable directives**. If any service is missing a definition, or if definitions differ in their locations, arguments, or argument types, a composition error occurs.

My take away from this statement is that each subgraph should each define and share the same rate limiting directive name(s).

**Comment by sbilello** [comment]
After googling around: https://github.com/apollographql/federation/issues/831
It looks like that it might work without managed federation
