### ISSUE TITLE
Rate limit not working

### ISSUE THREAD

**Issue by joshbenaron** [ravangen/graphql-rate-limit#236]
Hey - this is most likely my error, but just to help me out. My rate limiter isn't working. The `console.log` line isn't printing meaning it's never hit. I verified this with the debugger. Do you know why it's not working for me? Thank you in advance!

EDIT: Also the actual rate limiting isn't working. I can still spam it.

```gql
type Query @rateLimit(limit: 1, duration: 6000) {
    transaction(ids: [String]): [Transaction]
    peer: Peer
    account(external: Boolean, addresses: [String]): [Account!]!
}

type Transaction {
    id: String!
    owner: String!
    tags: [Tag]!
    target: String!
    data_size: BigInt!
    fee: BigInt!
    signature: String!
}

...
```

```ts
  // IMPORTANT: Specify how a rate limited field should determine uniqueness/isolation of operations
  // Uses the combination of user specific data (their ip) along the type and field being accessed
  const keyGenerator = (_, __, ___, context, ____) => {
    console.log(context.ip);
    return `${context.ip}`;
  };

  const db = new BundlerAPI(connection);
  return new ApolloServer({
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    typeDefs: [createRateLimitTypeDef(), typeDefs],
    resolvers,
    dataSources: () => ({ db }),
    schemaDirectives: {
      rateLimit: createRateLimitDirective({
        keyGenerator
      }),
    },
  });
```
```gql
// Query I'm executing
query ExampleQuery {
  transaction {
    id
  }
}
```

**Comment by juanboardera** [comment]
+1, rate limit does not seem to be working.

**Comment by ravangen** [comment]
👋 I will take a closer look on the weekend. I realize the examples are out of date for example.

**Comment by simlu** [comment]
Rate limiting is no longer working when upgrading `apollo-server-lambda` to `3.3.0` - on the `2.25.1` it seems to work fine

**Comment by ravangen** [comment]
Hey all, thank you for the details. As a sole maintainer, I have not been able to dig into this issue recently as I've been extra busy in my personal life for the past little while. The library is rather small, if someone wanted to dig in, I would appreciate the help in the short term. I would be happy to review any suggestions in the mean time until I can dig in.

**Comment by simlu** [comment]
@ravangen Appreciate you. Very much in the same boat with a lot of packages I maintain. I've taken a look and it looks like this issue does require a major rework. `Legacy Schema Directives and Directive Resolvers have been removed` as of [graphql-tools](https://github.com/ardatan/graphql-tools/blob/master/packages/schema/CHANGELOG.md#800) version 8.

This package relies heavily on those, and it's not a quick switchover. I've tried to do the migration for a bit, but tbh there is a lot I don't understand and the documentation is abysmal.

**Comment by ravangen** [comment]
I've pushed my work in progress to https://github.com/ravangen/graphql-rate-limit/pull/235. I think I updated the implementation to match the new `graphql-tools` approach, but I still have to update the tests and documentation.

I hope to continue poking at this issue, and the `graphql-tools` upgrade this week.

**Comment by ravangen** [comment]
@joshbenaron @juanboardera @simlu Can you let me know which version of dependencies you are using? 

As [mentioned earlier in this thread](https://github.com/ravangen/graphql-rate-limit/issues/236#issuecomment-946195764): `Legacy Schema Directives and Directive Resolvers have been removed` ([CHANGELOG](https://github.com/ardatan/graphql-tools/blob/master/packages/schema/CHANGELOG.md#800)). This is a breaking change between `graphql-tools` 7 and 8 (and also `apollo-server` 2 and 3). They stop using `schemaDirectives` option (what applies the rate limiting behaviour to where `@rateLimit` directive is annotated) in favour of transform that uses [`graphql-tools` `mapSchema`](https://www.graphql-tools.com/docs/schema-directives#implementing-schema-directives). In July 2021, both libraries had a major version upgrade which I suspect is related to the behaviour you are reporting soon thereafter.

I have just released [`graphql-rate-limit-directive` version 2](https://www.npmjs.com/package/graphql-rate-limit-directive/v/2.0.0) which switches to this new approach (see [migration guide](https://github.com/ravangen/graphql-rate-limit/blob/master/CHANGELOG.md#version-2-migration)). The tests pass and the examples work so I suspect it will resolve the issues you are reporting. I am going to close this issue as a result, but feel free to let me know if I missed something, and we can reopen this.

**Comment by simlu** [comment]
@ravangen Using 
```
apollo-server-lambda = "3.5.0"
apollo-server-tools =  "3.0.8"
graphql = "15.7.2"
graphql-rate-limit-directive = "2.0.0"
@graphql-tools/schema = "8.3.1"
```

Can confirm that after updating and following the migration guide this works again 🎉
