### ISSUE TITLE
Question: How are the rate limits applied?

### ISSUE THREAD

**Issue by adavis** [ravangen/graphql-rate-limit#303]
### How are the rate limits applied?

Are the rate limits applied per authenticated user or per IP address?

Thanks.

**Comment by ravangen** [comment]
Depends on the [`keyGenerator`](https://github.com/ravangen/graphql-rate-limit/blob/a7ac9a3786517fbec2f44af621adbc538fdbeb71/README.md#keygenerator). By default, it is just the [schema coordinates](https://github.com/ravangen/graphql-rate-limit/blob/a7ac9a3786517fbec2f44af621adbc538fdbeb71/src/index.ts#L169-L185) as this library doesn't make any assumptions about the server/context it is running under. See the [context example](https://github.com/ravangen/graphql-rate-limit/tree/master/examples/context) on limiting per ip.

**Comment by adavis** [comment]
Ok, thanks!
