### ISSUE TITLE
Update @graphql-tools/utils to v9

### ISSUE THREAD

**Issue by maxpain** [ravangen/graphql-rate-limit#317]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/5875582/202849186-7940f9b2-ac71-46f0-b25c-427f25ae3625.png">

**Comment by ravangen** [comment]
Should be fixed with https://github.com/ravangen/graphql-rate-limit/pull/314 and https://github.com/ravangen/graphql-rate-limit/pull/319
