### ISSUE TITLE
Using rate limiting with graphQL loadSchemaSync

### ISSUE THREAD

**Issue by joaogsousa** [ravangen/graphql-rate-limit#354]
We have a graphQL federation setup, in which the main graphQL schema is composed of sub-schemas defined by several microservices. 

For this to work each microservice needs to call loadSchemaSync(), then there will be some magic that will merge the provided schema with the schemas provided by other microservices.

But, when I use the rateLimit directive, the call to loadSchemaSync() fails. With the following error:

`[14:35:45.466] ERROR (21608): An Error in starting Jigsaw, Unknown directive "@rateLimit".
    stack: "Error: Unknown directive \"@rateLimit\".\n    at assertValidSDL (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\graphql\validation\validate.js:135:11)\n    at buildASTSchema (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\graphql\utilities\buildASTSchema.js:44:34)\n    at makeExecutableSchema (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\@graphql-tools\schema\cjs\makeExecutableSchema.js:73:47)\n    at mergeSchemas (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\@graphql-tools\schema\cjs\merge-schemas.js:32:63)\n    at getSchemaFromSources (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\@graphql-tools\load\cjs\schema.js:56:46)\n    at loadSchemaSync (D:\jh-trabalho\findmypast\workspace\jigsaw\node_modules\@graphql-tools\load\cjs\schema.js:32:12)\n    at createApolloServer (D:\jh-trabalho\findmypast\workspace\jigsaw\src\graphql\apollo-server.ts:31:30)\n    at server (D:\jh-trabalho\findmypast\workspace\jigsaw\src\server.ts:117:42)\n    at async startServer (D:\jh-trabalho\findmypast\workspace\jigsaw\src\main.ts:12:5)"`

I think I did the rateLimit setup right:
![image](https://github.com/ravangen/graphql-rate-limit/assets/5272399/f19451c2-0859-4010-96b4-1e0b5f3910e6)
![image](https://github.com/ravangen/graphql-rate-limit/assets/5272399/c8facd68-f9f1-4fd8-8dee-0ee2b0c5d983)

Does this lib support adding the rateLimitDirectiveTypeDefs through the graphQL tool loadSchemaSync() ?

**Comment by ravangen** [comment]
A reproduction repository/code would be appreciated instead of images. I haven't personally used federation/async loading.

I suspect we have all the necessary data, that it would be more a matter of calling `graphql-tools` functions with the right options and order of operations. This library's code conforms to the [suggest approach according to their docs](https://the-guild.dev/graphql/tools/docs/schema-directives#implementing-schema-directives).

**Comment by ravangen** [comment]
Not sure about the exact way to achieve this, but what if you make an basic schema with the directive (and transformer applied), and have your additional schemas merged together. In isolation the partial schemas may be invalid, but together once loaded they would be known? Have a rateLimiter schema exported from a module as a `GraphQLSchema` object, and use the [`ModuleLoader `](https://the-guild.dev/graphql/tools/docs/api/classes/loaders_module_src.ModuleLoader)? Again, haven't tried it, just theorizing.

**Comment by joaogsousa** [comment]
Hummm will try, thanks for the help!

**Comment by joaogsousa** [comment]
An update that I could get rid of the error by adding the directive directly on the graphQL schema instead of using typeDefs:
![image](https://github.com/ravangen/graphql-rate-limit/assets/5272399/ab6620a1-a204-460b-8fd1-df122ecf7b7d)

The directive seems now to be loaded in the schema OK, but the rate limiting is not working. I cant find any keys related to the rate limit being added to redis and I do tons of requests without being rate limited.

**Comment by joaogsousa** [comment]
Added the directive in the schema and used the rateLimitDirectiveTransformer.

**Comment by ravangen** [comment]
Sounds like it is working, happy to hear! 😄
