### ISSUE TITLE
Upgrade peer dependency rate-limiter-flexible to version @4.0.0

### ISSUE THREAD

**Issue by hafaiedhmehdy** [ravangen/graphql-rate-limit#384]
Hello!

Great work on the project and the **well-crafted documentation**. 

I have a suggestion regarding the dependencies; The documentation instructs the installation of peer dependencies, which defaults to the latest `rate-limiter-flexible@4.0.0`, two major versions ahead of the project's current dependency, `rate-limiter-flexible@^2.0.0`. 

Could we consider upgrading the project's dependency to align with this?

Thanks for considering the upgrade.

**Comment by ravangen** [comment]
Yes, for sure. It is on the list of goals for this month as time permits. I was hoping to test it before bumping it.
