### ISSUE TITLE
Support for async key generators

### ISSUE THREAD

**Issue by yunyu** [ravangen/graphql-rate-limit#78]
For when you want to limit based off of a user ID fetched from a database, etc...

**Comment by ravangen** [comment]
Hey @yunyu, thanks for the great suggestion! I was surprised to find this wasn't already supported.

I have released [version 1.1.0](https://github.com/ravangen/graphql-rate-limit/blob/master/CHANGELOG.md#110--2019-05-04) which now includes support for async key generators.

As a word of caution, inside a generator function, consider accessing the GraphQL `context` ([example](https://github.com/ravangen/graphql-rate-limit/blob/master/examples/context/index.js#L51-L55)) or memoizing any expensive calls (HTTP, database, ...) as the functions is run for each rate limited field.
